### ISSUE TITLE
Make support for strict mode on/off one 1 route

### ISSUE THREAD

**Issue by Casperhr** [nodes-php/api#14]
We need to have support for just making 1 route non-strict

In my case where I need to implement a webhook, I cannot get a header so I needed to set full project to non-strict

**Comment by rugaard** [comment]
I'm really not fan of these edge-case/project specific stuff :/

Why is it that you just can't make an ordinary route with:

```
Route::get('/api/webhook', 'WebhooksController@index');
```

And then use the API trait in that controller to return a transformed response. And if you only need to return an array as a response, you can use Laravel's own `view()` method:

```
return response()->json(['name' => 'Nodes']);
```

**Comment by Casperhr** [comment]
The webhook is posting data, and whatever route I post to, dingo takes over and asks for headers. 
Even if the route does not exist

**Comment by rugaard** [comment]
Even if you register the route with `Route::post()` instead of `api_post()` because that shouldn't happen. When using Laravel's own `Route` facade it shouldn't be registered with Dingo.

**Comment by Casperhr** [comment]
Yep that still happens. 

It's also kinda weird that you cannot make a 404 without the header, it will fail on the missing header first. 

Maybe it has something to do with it

**Comment by rugaard** [comment]
It definitely shouldn't overrule the ordinary `Route` facade.

**Comment by Casperhr** [comment]
The strict mode off was LAST option, I tried everything else. Clean routes, controllers, but dingo takes over!

**Comment by Casperhr** [comment]
This is now fixed with newest release of dingo
