### ISSUE TITLE
Call to undefined method - If you do not return any Response

### ISSUE THREAD

**Issue by Casperhr** [nodes-php/api#2]
"message": "Fatal error: Call to undefined method Illuminate\Http\Response::getStatusCodeAndMessage()",
  "code": 500,
  "debug": {
    "class": "Symfony\Component\Debug\Exception\FatalThrowableError",
    "file": "/var/www/riide/htdocs/vendor/nodes/api/src/Http/Response.php",
    "line": 68,
    "trace": [

We should consider just returning blank or an error people understand

**Comment by rugaard** [comment]
Can you post a snippet of where this error happens?

**Comment by Casperhr** [comment]
Just make an empty action

**Comment by Casperhr** [comment]
Is fixed now, but use strict return type to Response on all your actions
