### ISSUE TITLE
Installation script should create project namespace mapping to 'project' folder

### ISSUE THREAD

**Issue by rtrzebinski** [nodes-php/api#20]
In this example project name is 'Red24'

STR:
- create php class 'Bar' in projects/Foo/Bar.php
- class should be declared in 'Red24\Foo' namespace
- try to instantiate class - it won't be find by autoloader

FIX:

in composer.json change:

```
"autoload": {
    "classmap": [
        "database",
        "project"
    ],
    "psr-4": {
        "App\\": "app\/"
    }
```

to

```
"autoload": {
    "classmap": [
        "database",
        "project"
    ],
    "psr-4": {
        "App\\": "app\/",
        "Red24\\": "project\/"
    }
```

and run 'composer dump-autoload'

**Comment by rugaard** [comment]
This is duplicate bug of https://github.com/nodes-php/api/issues/10 :)

**Comment by rtrzebinski** [comment]
@rugaard not really, it's a different issue

**Comment by rugaard** [comment]
@rtrzebinski But it's the same bug :)

**Comment by rugaard** [comment]
Fixed in latest release: https://github.com/nodes-php/api/releases/tag/0.1.22
